############################################################
# +------------------------------------------------------+ #
# |                     ${name}                      | #
# +------------------------------------------------------+ #
############################################################

# Plugin created by SecretX (github.com/SecretX33)
# Version ${version}

# ${name} allows players to use wands that have various effects

# This file will NEVER get modified after being created, when updating the plugin please make sure you rename this one and let a new one be created, and copy your old configs to the new config file.

############################################################
# +------------------------------------------------------+ #
# |                   General Settings                   | #
# +------------------------------------------------------+ #
############################################################

# Enable spell effects
enable-effects: true
# Show message when cycling selected spell
enable-message-on-spell-switch: true
# Disable spell cooldowns GLOBALLY (use with CAUTION)
disable-all-cooldowns: false
# Disable fuel usage GLOBALLY (use with CAUTION)
disable-fuel-usage: false

# list of all spell properties
spells:
  # spell name
  leap:
    learn-price: 100          # price to learn it
    fuel-usage: 5             # how much fuel the spell is going to use
    cooldown: 7               # spell cooldown, in seconds
    height-multiplier: 0.8    # how high will the player leap
    distance-multiplier: 1.3  # how far the player will leap

  thrust:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    range: 15                 # up until what range the player can thrust others, in blocks
    height-multiplier: 0.7    # how high the player's target will be thrust
    distance-multiplier: 1.4  # how far the player's target will be thrust

  blink:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    range: 15                 # up until what range the player can blink, in blocks

  blind:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    duration: 5
    range: 8                 # up until what range the player can blind others, in blocks

  poison:
    learn-price: 100
    fuel-usage: 10
    cooldown: 15
    duration: 7
    range: 7                 # up until what range the player can poison others, in blocks

  vanish:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    duration: 5

  ensnare:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    duration: 5              # DON'T USE VALUE LOWER THAN 2
    range: 6                 # up until what range the player can trap others, in blocks

# Material list here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html, Ctrl + F is your friend
# Add as many fuels as you want, just don't leave this list empty
spell-fuel:
  - COAL
  - CHARCOAL