############################################################
# +------------------------------------------------------+ #
# |                     ${name}                      | #
# +------------------------------------------------------+ #
############################################################

# Plugin created by SecretX (github.com/SecretX33)
# Version ${version}

# ${name} allows players to use wands that have various effects

# This file will NEVER get modified after being created, when updating the plugin please make sure you rename this one and let a new one be created, and copy your old configs to the new config file.

############################################################
# +------------------------------------------------------+ #
# |                   General Settings                   | #
# +------------------------------------------------------+ #
############################################################

# Enable spell effects GLOBALLY
enable-spell-effects: true
# Show message when cycling selected spell
enable-message-on-spell-switch: true
# Disable spell cooldowns GLOBALLY (use with CAUTION)
disable-all-cooldowns: false
# Disable fuel usage GLOBALLY (use with CAUTION)
disable-fuel-usage: false

# list of all spell properties
spells:
  # spell name
  leap:
    learn-price: 100          # price to learn it
    fuel-usage: 5             # how much fuel the spell is going to use
    cooldown: 7               # spell cooldown, in seconds
    height-multiplier: 0.8    # how high will the player leap
    distance-multiplier: 1.3  # how far the player will leap
    effect:
      enabled: true
      type: BALL_LARGE        # valid values: BALL, BALL_LARGE, BURST, CREEPER, STAR
      main-color:
        - 151, 58, 208        # RGB, do like this "r, g, b" format to use a single color, is mandatory to have at least one value
      fade-color:
        - 112, 212, 99        # RGB, leave it empty to disable fade color completely
      flicker: true           # true if this explosion has the Twinkle effect (glowstone dust)
      trail: true             # true if this explosion has the Trail effect (diamond)

  thrust:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    range: 15                 # up until what range the player can thrust others, in blocks
    height-multiplier: 0.7    # how high the player's target will be thrust
    distance-multiplier: 1.4  # how far the player's target will be thrust
    effect:
      enabled: true
      type: BALL_LARGE
      main-color:
        - 151, 58, 208         # you can put multiple colors like this
        - 54, 81, 155          # in a list format
        - 211, 120, 175
      fade-color:
        - 112, 212, 99         # and of course, multiple fade colors
        - 184, 139, 35         # as well in the same list format
      flicker: true
      trail: true

  blink:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    range: 15                 # up until what range the player can blink, in blocks
    effect:
      enabled: true
      type: BALL_LARGE
      main-color: 
        - 151, 58, 208 
      fade-color: []          # this one doesn't have any fade color effects
      flicker: true
      trail: true

  blind:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    duration: 5
    range: 8                 # up until what range the player can blind others, in blocks
    effect:
      enabled: true
      type: BALL_LARGE
      main-color: 
        - 151, 58, 208 
      fade-color: 
        - 112, 212, 99
      flicker: true
      trail: true

  poison:
    learn-price: 100
    fuel-usage: 10
    cooldown: 15
    duration: 7
    range: 7                  # up until what range the player can poison others, in blocks
    effect:
      enabled: true
      type: BALL_LARGE
      main-color: 
        - 151, 58, 208 
      fade-color: 
        - 112, 212, 99
      flicker: true
      trail: true

  vanish:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    duration: 5
    effect:
      enabled: true
      type: BALL_LARGE
      main-color: 
        - 151, 58, 208 
      fade-color: 
        - 112, 212, 99
      flicker: true
      trail: true

  ensnare:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    duration: 5               # DON'T USE VALUE LOWER THAN 2
    range: 6                  # up until what range the player can trap others, in blocks
    effect:
      enabled: true
      type: BALL_LARGE
      main-color: 
        - 151, 58, 208 
      fade-color: 
        - 112, 212, 99
      flicker: true
      trail: true

# Material list here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html, Ctrl + F is your friend
# Add as many fuels as you want, just don't leave this list empty
spell-fuel:
  - COAL
  - CHARCOAL