############################################################
# +------------------------------------------------------+ #
# |                     ${name}                      | #
# +------------------------------------------------------+ #
############################################################

# Plugin created by SecretX (github.com/SecretX33)
# Version ${version}

# ${name} allows players to use wands that have various effects

# This file will NEVER get modified after being created, when updating the plugin please make sure you rename this one and let a new one be created, and copy your old configs to the new config file.

############################################################
# +------------------------------------------------------+ #
# |                   General Settings                   | #
# +------------------------------------------------------+ #
############################################################

# Enable spell effects GLOBALLY
enable-spell-effects: true
# Show message when cycling selected spell
enable-message-on-spell-switch: true
# Disable spell cooldowns GLOBALLY (use with CAUTION)
disable-all-cooldowns: false
# Disable fuel usage GLOBALLY (use with CAUTION)
disable-fuel-usage: false
# Delete wand on player death (dying is scarier now, huh?)
delete-wand-on-death: false
# Remove spellteachers if its World is not found (if the plugin cannot find the world, it'll remove the SpellTeacher automatically and warn in the console)
remove-spellteacher-from-db-if-world-not-found: true
# Delay between notifications for "spell is in cd" message, in seconds. This config will ignore /wand reload because of limitations and will only be reapplied when you restart the server.
cooldown-for-notifying-spell-is-cd: 2.0
# If true and ProtocolLib is present, players will only be able to see their own dropped wands on the ground. This config will also ignore /wand reload because of limitations.
players-only-see-their-own-wands: true
# Prevent fall damage after using leap for X seconds, increase if you feel like it's not enough. This config will ignore /wand reload.
player-immune-to-fall-damage-after-leaping-for: 3.5

############################################################
# +------------------------------------------------------+ #
# |                    Spell Settings                    | #
# +------------------------------------------------------+ #
############################################################

# list of all spell properties
spells:
  # spell name
  leap:
    learn-price: 100.0         # price to learn it
    fuel-usage: 5              # how much fuel the spell is going to use
    cooldown: 7.0              # spell cooldown, in seconds
    height-multiplier: 0.8     # how high will the player leap
    distance-multiplier: 1.3   # how far the player will leap
    effect:
      enabled: true
      type: BALL_LARGE         # valid values: BALL, BALL_LARGE, BURST, CREEPER, STAR
      main-color:
        - 151, 58, 208         # RGB, do like this "r, g, b" format to use a single color, is mandatory to have at least one value
      fade-color:
        - 112, 212, 99         # RGB, leave it empty to disable fade color completely
      flicker: true            # true if this explosion has the Twinkle effect (glowstone dust)
      trail: true              # true if this explosion has the Trail effect (more particles & they stay longer)

  thrust:
    learn-price: 100.0
    fuel-usage: 10
    cooldown: 12.0
    range: 15                  # up until what range the player can thrust others, in blocks
    height-multiplier: 0.7     # how high the player's target will be thrust
    distance-multiplier: 1.4   # how far the player's target will be thrust
    effect:
      enabled: true
      type: BURST
      main-color:
        - 151, 58, 208         # you can put multiple colors like this
        - 54, 81, 155          # in a list format
        - 211, 120, 175
      fade-color:
        - 112, 212, 99         # and of course, multiple fade colors
        - 184, 139, 35         # as well in the same list format
      flicker: false
      trail: false

  blink:
    learn-price: 100.0
    fuel-usage: 10
    cooldown: 12.0
    range: 15                  # up until what range the player can blink, in blocks
    effect:
      enabled: true
      type: BALL
      main-color:
        - 229, 84, 84
      fade-color: []           # this one doesn't have any fade color effects
      flicker: true
      trail: true

  blind:
    learn-price: 100.0
    fuel-usage: 10
    cooldown: 12.0
    duration: 5.0
    range: 8                   # up until what range the player can blind others, in blocks
    effect:
      enabled: true
      type: BALL_LARGE
      main-color:
        - 151, 58, 208
      fade-color:
        - 112, 212, 99
      flicker: false
      trail: false

  ensnare:
    learn-price: 100.0
    fuel-usage: 10
    cooldown: 12.0
    duration: 5.0
    range: 6                       # up until what range the player can trap others, in blocks
    mining-fatigue-potency: 1      # add mining fatigue to make escape the trap more challenging, read about it here https://minecraft.fandom.com/wiki/Mining_Fatigue for more information about what changes in each potency, optionally use 0 to disable the effect
    mining-fatigue-duration: 3.0   # how many seconds the mining fatigue will last
    effect:
      enabled: true
      type: BALL_LARGE
      main-color:
        - 244, 251, 19
      fade-color:
        - 251, 166, 19
      flicker: true
      trail: true

  poison:
    learn-price: 100.0
    fuel-usage: 10
    cooldown: 15.0
    duration: 7.0
    range: 7                    # up until what range the player can poison others, in blocks
    poison-potency: 7           # what potency of poison will be applied, valid values: 1-31, by my tests around 7 to 9 is where the poison is stronger, because after 9 there's a grace period in which the player cannot take damage
    effect:
      enabled: true
      type: BALL_LARGE
      main-color:
        - 54, 234, 54
      fade-color:
        - 194, 225, 74
      flicker: true
      trail: false

  vanish:
    learn-price: 100.0
    fuel-usage: 10
    cooldown: 12.0
    duration: 5.0
    full-invisible: false         # if false, player's item in hand will still be visible, if true then it renders the player COMPLETELY invisible while under vanish, even while holding items in the hand, but as a side effect nobody can damage the player with melee in the meantime
    effect:
      enabled: true
      type: BALL_LARGE
      main-color:
        - 151, 58, 208
      fade-color:
        - 112, 212, 99
      flicker: true
      trail: true

  slow:
    learn-price: 100.0
    fuel-usage: 8
    cooldown: 15.0
    duration: 3.0
    range: 8
    potency: 2
    effect:
      enabled: true
      type: BALL_LARGE
      main-color:
        - 151, 58, 208
      fade-color:
        - 112, 212, 99
      flicker: false
      trail: false

############################################################
# +------------------------------------------------------+ #
# |                 Spell Fuel Settings                  | #
# +------------------------------------------------------+ #
############################################################

# Material list here https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html, Ctrl + F is your friend, use the name exactly as listed in the website
# Add as many fuels as you want, just don't leave this list empty
spell-fuel:
  - COAL
  - CHARCOAL
