############################################################
# +------------------------------------------------------+ #
# |                     ${name}                      | #
# +------------------------------------------------------+ #
############################################################

# Plugin created by SecretX (github.com/SecretX33)
# Version ${version}

# ${name} allows you to use wands that have various effects

# This file will NEVER get modified after being created, when updating please make sure you rename this one and let a new one be created, and copy your old configs to the new config file.

############################################################
# +------------------------------------------------------+ #
# |                   General Settings                   | #
# +------------------------------------------------------+ #
############################################################

# Enable spell effects
enable-effects: true

# list of all spell properties
spells:
  # spell name
  leap:
    learn-price: 100  # price to learn it
    fuel-usage: 5     # how much fuel the spell is going to use
    cooldown: 7       # cooldown, in seconds

  blink:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12

  blind:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    duration: 5

  poison:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    duration: 5

  vanish:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    duration: 5

  ensnare:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12
    duration: 5

  thrust:
    learn-price: 100
    fuel-usage: 10
    cooldown: 12

# Add as many fuels as you want, just don't leave this list empty
spell-fuel:
  - COAL
  - CHARCOAL