############################################################
# +------------------------------------------------------+ #
# |                     ${name}                      | #
# +------------------------------------------------------+ #
############################################################

# Plugin created by SecretX (github.com/SecretX33)
# Version ${version}

# ${name} allows you to use wands that have various effects

# This file will NEVER get modified after being created, when updating please make sure you rename this one and let a new one be created, and copy your old configs to the new config file.

############################################################
# +------------------------------------------------------+ #
# |                   General Settings                   | #
# +------------------------------------------------------+ #
############################################################

# Enable spell effects
enable-effects: true
