name: ${name}
version: ${version}
main: com.github.secretx33.magicwands.MagicWands
api-version: 1.16
authors: [SecretX]
description: Magic wands, for everyone.
website: https://github.com/SecretX33
depend: [ProtocolLib, Vault]

commands:
  wand:
    description: ${name}
    usage: /<command> <sub> [parameters]

permissions:

  magicwands.*:
    description: Gives access to all ${name} commands. Default to players with op.
    default: op
    children:
      magicwands.reload: true
      magicwands.spell: true
      magicwands.skins: true
      magicwands.skins.stick: true
      magicwands.skins.bone: true
      magicwands.skins.blaze_rod: true

  magicwands.reload:
    description: Allows one to reload all plugin configurations.
    default: false

  magicwands.spell:
    description: Grant access to the command 'spell'.
    default: false

  magicwands.skins:
    description: Grand access to the command 'changeskin'.
    default: false

  magicwands.skins.stick:
    description: Grand access to the Stick wand skin.
    default: false

  magicwands.skins.bone:
    description: Grand access to the Bone wand skin.
    default: false

  magicwands.skins.blaze_rod:
    description: Grand access to the Blaze Rod wand skin.
    default: false
