name: ${name}
version: ${version}
main: com.github.secretx33.magicwands.MagicWands
api-version: 1.16
authors: [SecretX]
description: Magic wands, for everyone.
website: https://github.com/SecretX33
depend: [ProtocolLib, Vault]

commands:
  wand:
    description: ${name}
    usage: /<command>

permissions:
  magicwands.*:
    description: Gives access to all ${name} commands. Default to players with op.
    default: op
    children:
      magicwands.edit: true
  magicwands.edit:
    description: Allows a player to create, mark, unmark and edit "quest" chests
    default: false
